# Generated by Django 4.1.5 on 2023-01-24 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('like', models.BooleanField(default=False)),
                ('comment', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
