# Generated by Django 4.1.5 on 2023-01-24 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stagram', '0002_alter_post_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='comment',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
